# Generated by Django 5.2.5 on 2025-08-27 18:30

import apps.payments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=apps.payments.models.generate_short_uuid, max_length=24, unique=True, verbose_name='invoice number')),
                ('html_string', models.TextField(blank=True, help_text='HTML content of the invoice', null=True, verbose_name='HTML String')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('waafi', 'Waafi'), ('cac', 'Cac Pay'), ('saba', 'Saba Pay'), ('boa', 'Boa Pay'), ('bci', 'BCI Pay')], max_length=20, verbose_name='Method')),
                ('status', models.CharField(choices=[('pending', 'On hold'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20, verbose_name='Status')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='ReservationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_number', models.CharField(default=apps.payments.models.generate_short_uuid, max_length=24, unique=True, verbose_name='Reservation notice number')),
                ('html_string', models.TextField(blank=True, help_text='HTML content of the reservation notice', null=True, verbose_name='HTML String')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Reservation notice',
                'verbose_name_plural': 'Reservation notices',
                'db_table': 'reservation_notices',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=apps.payments.models.generate_short_uuid, max_length=24, unique=True, verbose_name='ticket number')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Issued at')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('html_string', models.TextField(blank=True, help_text='HTML content of the ticket', null=True, verbose_name='HTML String')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
