name: "edr_development"

volumes:
  edr_local_db_data: {}

services:
  django: &django
    build: 
      context: .
      dockerfile: /docker/local/Dockerfile
    image: edr_local_django
    container_name: edr_local_django
    volumes:
      - .:/project
    ports:
      - 8000:8000
    env_file:
      - ./.env
    command: /start
    depends_on:
      - postgres
      - mailpit

  postgres:
    image: postgres:16-alpine
    container_name: edr_local_postgres
    ports:
      - 5432:5432
    volumes:
      - edr_local_db_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: edr_local_mailpit
    ports:
      - "8025:8025"
