# Generated by Django 5.2.5 on 2025-08-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='City name')),
                ('country', models.CharField(max_length=128, verbose_name='Country name')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'db_table': 'destination',
            },
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('category', models.CharField(choices=[('0-10', '0 to 10 kg (inclusive)'), ('11-20', '11 to 20 kg'), ('21-30', '21 to 30 kg'), ('31-40', '31 to 40 kg'), ('40+', '+40 kg')], default='0-10', max_length=20, verbose_name='Category')),
                ('extra_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Extra fee')),
            ],
            options={
                'verbose_name': 'Luggage',
                'verbose_name_plural': 'Luggage',
                'db_table': 'luggage',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('name', models.CharField(max_length=128, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=24, null=True, verbose_name='Phone Number')),
                ('birth_date', models.DateField(null=True, verbose_name='Date of birth')),
                ('identity_document', models.FileField(null=True, upload_to='passports/', verbose_name='Identity document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'db_table': 'passengers',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_arrivals', to='reservations.destination', verbose_name='Arrival city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_departures', to='reservations.destination', verbose_name='Departure city')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'db_table': 'price',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('ticket_type', models.CharField(choices=[('one_way', 'One-way ticket'), ('round_trip', 'Round-trip ticket')], default='one_way', max_length=24, verbose_name='Ticket type')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total amount')),
                ('passengers', models.ManyToManyField(related_name='reservations', to='reservations.passenger', verbose_name='Passengers')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time on which the object was updated.', verbose_name='Updated at')),
                ('departure_date', models.DateField(verbose_name='Departure date')),
                ('arrival_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='reservations.destination', verbose_name='Arrival city')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='reservations.destination', verbose_name='Departure city')),
                ('luggage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.luggage', verbose_name='Luggage')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Travel',
                'verbose_name_plural': 'Travel',
                'db_table': 'travel',
            },
        ),
    ]
